const itemData = {
	items: [
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 44,
			property_type: "house",
			location: "Indonasia",
			room: 1,
			bed: 2,
			bathroom: 1,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 8,
			infants: 2,
		},
		{
			name: "Villa near dive sites",
			category_name: "Rooms",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 140,
			property_type: "house",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 1,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Villa near dive sites",
			category_name: "Mansions",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 90,
			property_type: "apartment",
			location: "Indonasia",
			room: 5,
			bed: 8,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 15,
			infants: 5,
		},
		{
			name: "Asi villa",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "apartment",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 10,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Treasure of Bali",
			category_name: "Cabins",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 200,
			property_type: "guesthouse",
			location: "Seririt, Bali, Indonesia",
			room: 2,
			bed: 3,
			bathroom: 2,
			checkin_avalable: "2023-08-22",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Treasure of Bali",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 320,
			property_type: "hostel",
			location: "Seririt, Bali, Indonesia",
			room: 2,
			bed: 3,
			bathroom: 2,
			checkin_avalable: "2023-08-22",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 44,
			property_type: "house",
			location: "Indonasia",
			room: 1,
			bed: 2,
			bathroom: 1,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 8,
			infants: 2,
		},
		{
			name: "Villa near dive sites",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 15,
			property_type: "house",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 1,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Treasure of Bali",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 34,
			property_type: "guesthouse",
			location: "Seririt, Bali, Indonesia",
			room: 2,
			bed: 4,
			bathroom: 2,
			checkin_avalable: "2023-08-22",
			checkout_avalable: "2024-09-20",
			adaltguest: 4,
			infants: 1,
		},
		{
			name: "Dome - Bamboo Villa",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 44,
			property_type: "guesthouse",
			location: "Tampaksiring, Bali, Indonesia",
			room: 3,
			bed: 5,
			bathroom: 3,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 8,
			infants: 2,
		},
		{
			name: "Villa near dive sites",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 26,
			property_type: "house",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 1,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Asi villa",
			category_name: "Beach",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 43,
			property_type: "hostel",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 10,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Asi villa",
			category_name: "Beach",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 66,
			property_type: "apartment",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 6,
			bathroom: 4,
			checkin_avalable: "2023-08-30",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Asi villa",
			category_name: "Beach",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "gusethouse",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 10,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Asi villa",
			category_name: "Beach",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 77,
			property_type: "apartment",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 10,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Treasure of Bali",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "house",
			location: "Seririt, Bali, Indonesia",
			room: 2,
			bed: 3,
			bathroom: 2,
			checkin_avalable: "2023-08-22",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Asi villa",
			category_name: "Caves",
			image: "https://i.ibb.co/Kbk3d0J/cabin.jpg",
			price: 163,
			property_type: "house",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 10,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Treasure of Bali",
			category_name: "Cabins",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 132,
			property_type: "hostel",
			location: "Seririt, Bali, Indonesia",
			room: 2,
			bed: 3,
			bathroom: 2,
			checkin_avalable: "2023-08-22",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 83,
			property_type: "house",
			location: "Indonasia",
			room: 1,
			bed: 2,
			bathroom: 1,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 8,
			infants: 2,
		},
		{
			name: "Villa near dive sites",
			category_name: "Rooms",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 40,
			property_type: "house",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 1,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Villa near dive sites",
			category_name: "Mansions",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 40,
			property_type: "apartment",
			location: "Indonasia",
			room: 5,
			bed: 8,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 15,
			infants: 5,
		},
		{
			name: "Asi villa",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "apartment",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 10,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Treasure of Bali",
			category_name: "Cabins",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 78,
			property_type: "guesthouse",
			location: "Seririt, Bali, Indonesia",
			room: 2,
			bed: 3,
			bathroom: 2,
			checkin_avalable: "2023-08-22",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Treasure of Bali",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "hostel",
			location: "Seririt, Bali, Indonesia",
			room: 2,
			bed: 3,
			bathroom: 2,
			checkin_avalable: "2023-08-22",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 44,
			property_type: "house",
			location: "Indonasia",
			room: 1,
			bed: 2,
			bathroom: 1,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 8,
			infants: 2,
		},
		{
			name: "Villa near dive sites",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 40,
			property_type: "house",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 1,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Treasure of Bali",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "guesthouse",
			location: "Seririt, Bali, Indonesia",
			room: 2,
			bed: 4,
			bathroom: 2,
			checkin_avalable: "2023-08-22",
			checkout_avalable: "2024-09-20",
			adaltguest: 4,
			infants: 1,
		},
		{
			name: "Dome - Bamboo Villa",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 44,
			property_type: "guesthouse",
			location: "Tampaksiring, Bali, Indonesia",
			room: 3,
			bed: 5,
			bathroom: 3,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 8,
			infants: 2,
		},
		{
			name: "Villa near dive sites",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 40,
			property_type: "house",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 1,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Asi villa",
			category_name: "Beach",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "hostel",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 10,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Asi villa",
			category_name: "Beach",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "apartment",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 6,
			bathroom: 4,
			checkin_avalable: "2023-08-30",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Asi villa",
			category_name: "Beach",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "gusethouse",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 10,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Asi villa",
			category_name: "Beach",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "apartment",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 10,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Treasure of Bali",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 78,
			property_type: "house",
			location: "Seririt, Bali, Indonesia",
			room: 2,
			bed: 3,
			bathroom: 2,
			checkin_avalable: "2023-08-22",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
		{
			name: "Asi villa",
			category_name: "Caves",
			image: "https://i.ibb.co/Kbk3d0J/cabin.jpg",
			price: 78,
			property_type: "house",
			location: "Koh Samui, Surattani, Thailand",
			room: 4,
			bed: 10,
			bathroom: 6,
			checkin_avalable: "2023-08-28",
			checkout_avalable: "2024-09-20",
			adaltguest: 12,
			infants: 5,
		},
		{
			name: "Treasure of Bali",
			category_name: "Cabins",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 78,
			property_type: "hostel",
			location: "Seririt, Bali, Indonesia",
			room: 2,
			bed: 3,
			bathroom: 2,
			checkin_avalable: "2023-08-22",
			checkout_avalable: "2024-09-20",
			adaltguest: 3,
			infants: 1,
		},
	],
};

module.exports = itemData;
